services:
  redis:
    image: redis:alpine
    container_name: metaverse-redis
    networks:
      - metaverse-net

  app:
    image: ${DOCKER_IMAGE_NAME}
    container_name: metaverse-app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - metaverse-net

  nginx:
    image: nginx:alpine
    container_name: metaverse-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - metaverse-net

networks:
  metaverse-net:
    driver: bridge
